plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jorteron.phonetv'
    compileSdk 34

    defaultConfig {
        applicationId "com.jorteron.phonetv"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "0.1"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
